## Array creation

### Single array

In [34]:
import numpy as np

mylist = [1,2,3,4]
print(mylist)

nparray = np.array(mylist)
print(nparray)

[1, 2, 3, 4]
[1 2 3 4]


### Multi dimensional array

In [35]:
mylist2 = [*range(11,15)]

mylist3 = [mylist, mylist2]

nparray2 = np.array(mylist3)
nparray2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [36]:
#dimensions
print(nparray2.shape)

#type of objects in array 
nparray2.dtype

(2, 4)


dtype('int32')

### Special arrays

In [37]:
#array of zeros
zero_array = np.zeros(10)
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
zero_array.dtype

dtype('float64')

In [39]:
#array of 1's

one_array = np.ones([5,6])
one_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
#empty arrays
print(np.empty(5))
print(np.empty([3,3]))

[4.24399158e-314 8.48798317e-314 1.27319747e-313 1.69759663e-313
 2.12199579e-313]
[[1.06128212e-312 0.00000000e+000 1.06395697e+224]
 [7.41138105e-038 5.44306780e-062 1.43466004e-051]
 [4.76421391e-038 3.08740055e-085 6.27207943e-310]]


In [41]:
#identity matrix 
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Arange function

ref- https://realpython.com/how-to-use-numpy-arange/

In [42]:
#create an array with simple range
print(np.arange(0,10))

#create an array with step
print(np.arange(1,20,2))

#create an array in descending order
print(np.arange(10,0,-1))

#multidimensional array
print(np.arange(1,11).reshape((5,2)))


[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[10  9  8  7  6  5  4  3  2  1]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [43]:
#using linspace
linarray = np.linspace(0,5,10)
print(linarray)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
